//GETTERS
export const DOUBLE_COUNTER = "counter/DOUBLE_COUNTER";
export const STRING_COUNTER = "counter/STRING_COUNTER";
export const VALUE = "shared/VALUE";

//MUTATIONS
export const MUTATE_INCREMENT_COUNTER = "counter/MUTATE_INCREMENT_COUNTER";
export const MUTATE_DECREMENT_COUNTER = "counter/MUTATE_DECREMENT_COUNTER";
export const MUTATE_UPDATE_VALUE = "shared/MUTATE_UPDATE_VALUE";

//ACTIONS
export const INCREMENT_COUNTER = "counter/INCREMENT_COUNTER";
export const INCREMENT_COUNTER_ASYNC = "counter/INCREMENT_COUNTER_ASYNC";
export const DECREMENT_COUNTER = "counter/DECREMENT_COUNTER";
export const DECREMENT_COUNTER_ASYNC = "counter/DECREMENT_COUNTER_ASYNC";
export const UPDATE_VALUE = "shared/UPDATE_VALUE";
